### ISSUE TITLE
Crash on device orientation

### ISSUE THREAD

**Issue by shuvashish76** [VivekThazhathattil/dekadico#9]
**Crash logs**

```
FATAL EXCEPTION: main
Process: com.example.spokennumbers, PID: 14528
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.spokennumbers/com.example.spokennumbers.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.example.spokennumbers.spoken_numbers_ingame_fragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4702)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.example.spokennumbers.spoken_numbers_ingame_fragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:538)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851)
	at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85)
	at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
	at com.example.spokennumbers.MainActivity.onCreate(MainActivity.java:50)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
	... 10 more
Caused by: java.lang.NoSuchMethodException: <init> []
	at java.lang.Class.getConstructor0(Class.java:2320)
	at java.lang.Class.getConstructor(Class.java:1725)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:523)
	... 22 more
```
Crash when change orientation from 👇🏿
![Screenshot_2021-10-12-07-54-47](https://user-images.githubusercontent.com/48226312/136880622-08d8fd42-c672-4386-9d9b-59118bad74e3.jpeg)
![Screenshot_2021-10-12-07-54-37](https://user-images.githubusercontent.com/48226312/136880628-b352ff7b-c602-4be1-96af-3e8dab0ff119.jpeg)

(for some reason, it doesn't crash when on app main screen)

Thanks🙏🏿

**Comment by VivekThazhathattil** [comment]
Thank you for reporting. I'll look into it.

**Comment by VivekThazhathattil** [comment]
#13 will serve as a hotfix for this issue, until a better solution is obtained.
